id: I77F4AADD
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T13:31:56+00:00'
last_modified: '2022-06-08T01:43:38.251463+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN4936
  title: སྐོར་ཚོམས་སྟོང་ཐུན་བཅུ་གཅིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '9710':
      image_group_id: I3CN4938
      title: ''
      total_pages: 228
      order: 1
      base_file: 9710.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
