id: I77F4AADD
legacy_id: P004529
ocr_import_info:
  bdrc_scan_id: W3CN4936
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T13:30:30'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T11:50:11.102104+00:00'
last_modified: 2022-08-27 19:50:23.400628
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN4936
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN4936
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྐོར་ཚོམས་སྟོང་ཐུན་བཅུ་གཅིག
  author: གཡུ་ཐོག་གསར་མ་ཡོན་ཏན་མགོན་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.8808355206249017
  ocr_word_median_confidence_index: 0.9599999785423279
quality: null
bases:
  I3CN4938:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN4938
      total_pages: 228
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN4938.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.8808355206249017
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
