id: P004529
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 11:30:10.500699
source_metadata:
  id: bdr:W3CN4936
  title: སྐོར་ཚོམས་སྟོང་ཐུན་བཅུ་གཅིག
  author: ''
  volumes:
    337ca7b8da1441f0a34b230dfb01de33:
      image_group_id: I3CN4938
      title: ''
      volume_number: 1
      total_pages: 228
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
