id: P004529
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN4936
  title: སྐོར་ཚོམས་སྟོང་ཐུན་བཅུ་གཅིག
  author: ''
  volumes:
    337ca7b8da1441f0a34b230dfb01de33:
      image_group_id: I3CN4938
      title: ''
      volume_number: 1
      total_pages: 228
